version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zhilina
      POSTGRES_USER: zhilina
      POSTGRES_PASSWORD: zhilina
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  python_app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://zhilina:zhilina@db:5432/zhilina

